@startuml
!pragma layout smetana

' Déclaration des classes
class Jeu {
    --
    + initialiserJeu()
}
Jeu --> "1" Pioche : -pioche
Jeu --> "2" ZoneOffensive : -zoneOffensiveJoueur1, -zoneOffensiveJoueur2
Jeu --> "2" ZoneStrategique : -zoneStrategiqueJoueur1, -zoneStrategiqueJoueur2

class Pioche {
    --
    + ajouterCarte(carte : Carte)
    + piocher() : Carte
    + melanger()
    + estVide() : Boolean
    + getNombreCartes() : Integer
}

Pioche --> "{ordered} *" Carte : -cartes


class ZoneOffensive {
    --
    + ajouterCarte(carte : Carte)
    + getCartesOffensives() : List<CarteOffensive>
    + viderZone()
}
ZoneOffensive --> "{ordered} *" CarteOffensive : -cartes

class ZoneStrategique {
    --
    + ajouterCarte(carte : Carte)
    + getCartesStrategiques() : List<CarteStrategique>
    + viderZone()
}
ZoneStrategique --> "{ordered} *" CarteStrategique : -cartes

class Joueur {
    - vie: Integer = 5
    - popularite: Integer = 0
    - or: Integer = 3
    - nbCartes : Integer
    --
    + Joueur(pirate : Pirate)
    + getCarteSpecial(): Carte
    + getPointsDeVie() : Integer
    + setVie(vie : Integer) 

    + getPopularite() : Integer
    + setPopularite(popularite : Integer) 
    + getOr() : Integer
    + setOr(or : Integer)
    + getNbCartes() : Integer
    + setNbCartes(nbCartes : Integer)
    + getPirate() : Pirate
    + getNom() : String

    + perdrePointsDeVie(points : Integer)
    + gagnerPointsDeVie(points : Integer)
    + perdrePopularite(points : Integer)
    + gagnerPopularite(points : Integer)
    + perdreOr(montant : Integer)
    + gagnerOr(montant : Integer)

    + getMain() : List<Carte>
    + ajouterCarte(carte : Carte) 
    + retirerCarte(indexCarte : Integer) : Boolean
    
}
Joueur --> "1" Pirate : -pirate
Joueur --> "{ordered} 4" Carte : -main

class Pirate {
    - nom : String
    - vie : Integer
    - popularite : Integer
    - description : String
    - cheminImage : String
    - carteCoupSpecial : Carte
    --
    + Pirate(nom : String, vie : Integer, popularite : Integer, description : String, carteCoupSpecial : Carte)
    + Pirate(nom : String)
    + getNom() : String
    + getDescription() : String
    + setDescription(description : String)
    + getCarteSpecial() : Carte
    + getPopularite() : Integer
    + setPopularite(popularite : Integer)
    + getVie() : Integer
    + setVie(vie : Integer)
    + getCheminImage() : String
    + setCheminImage(cheminImage : String)
}

abstract class "<<abstract>> Carte" as Carte {
    - nomCarte : String
    - description : String
    - cout : Integer
    --
    + Carte(type : TypeCarte, nomCarte : String, description : String, cout : Integer)
    + Carte(type : TypeCarte, nomCarte : String, description : String)
    + getNomCarte() : String
    + setNomCarte(nomCarte : String) 
    + getDescription() : String
    + setDescription(description : String) 
    + getCout() : Integer
    + setCout(cout : Integer) 
    + getType() : TypeCarte
    + <<abstract>> effetCarte() : EffetCarte {abstract}
    + toString() : String
    + getDegatsInfliges() : Integer
    + getDegatsSubis() : Integer
    + getPopulariteGagnee() : Integer
    + getVieGagne() : Integer
    + getOrGagne() : Integer
    + <<abstract>> getCheminImage() : String {abstract}
}
Carte "1" *-- "1" "<<enumeration>> TypeCarte" : -type

' Classe abstraite CarteOffensive
abstract class "<<abstract>> CarteOffensive" as CarteOffensive extends Carte {
    - typeOffensif : TypeOffensif
    --
    + CarteOffensive(nomCarte : String, description : String, typeOffensif : TypeOffensif, cout : Integer)
    + CarteOffensive(nomCarte : String, description : String, typeOffensif : TypeOffensif)
    + getTypeOffensif() : TypeOffensif
    + setTypeOffensif(typeOffensif : TypeOffensif)  
    + estTresorOffensif() : Boolean
}


CarteOffensive *-- "1" "<<enumeration>> TypeOffensif" : -typeOffensif

' Classe CarteAttaque
class CarteAttaque extends CarteOffensive {
    - degatsInfliges : Integer
    - degatsSubis : Integer
    --
    + CarteAttaque(nomCarte : String, description : String, cout : Integer, degatsInfliges : Integer, degatsSubis : Integer)
    + CarteAttaque(nomCarte : String, description : String, degatsInfliges : Integer, degatsSubis : Integer)
    + effetCarte() : EffetCarte
    + getCheminImage() : String
}

' Classe CarteSoin
class CarteSoin extends CarteOffensive {
    - vieGagne : Integer
    --
    + CarteSoin(nomCarte : String, description : String, cout : Integer, pointsDeSoin : Integer)
    + CarteSoin(nomCarte : String, description : String, pointsDeSoin : Integer)
    + effetCarte() : EffetCarte
    + getCheminImage() : String
}

' Classe abstraite CarteStrategique
abstract class "<<abstract>> CarteStrategique" as CarteStrategique extends Carte {
    - typeStrategique : TypeStrategique
    --
    + CarteStrategique(nomCarte : String, description : String, typeStrategique : TypeStrategique, cout : Integer)
    + CarteStrategique(nomCarte : String, description : String, typeStrategique : TypeStrategique)
    + getTypeStrategique() : TypeStrategique
    + setTypeStrategique(typeStrategique : TypeStrategique)  
    + estPopularite() : Boolean
    + estTresor() : Boolean
}


CarteStrategique  *-- "1" "<<enumeration>> TypeStrategique" : -typeStrategique

' Classe CartePopularite
class CartePopularite extends CarteStrategique {
    - populariteGagnee : Integer
    - degatsSubis : Integer
    --
    + CartePopularite(nomCarte : String, description : String, cout : Integer, populariteGagnee : Integer, degatsSubis : Integer)
    + CartePopularite(nomCarte : String, description : String, populariteGagnee : Integer, degatsSubis : Integer)
    + effetCarte() : EffetCarte
    + getCheminImage() : String
}

' Classe CarteTresor
class CarteTresor extends CarteStrategique {
    - orGagne : Integer
    --
    + CarteTresor(nomCarte : String, description : String, cout : Integer, orGagne : Integer)
    + CarteTresor(nomCarte : String, description : String, orGagne : Integer)
    + effetCarte() : EffetCarte
    + getCheminImage() : String
}

' Enum TypeCarte
enum "<<enumeration>> TypeCarte" {
    OFFENSIVE
    STRATEGIQUE
}

' Enum TypeOffensif
enum "<<enumeration>> TypeOffensif" {
    ATTAQUE
    SOIN
}

' Enum TypeStrategique
enum "<<enumeration>> TypeStrategique" {
    POPULARITE
    TRESOR
}

' Classe ControlJeu
class ControlJeu {
    - joueurActif : Integer
    
    --
    + ControlJeu()
    + initialiserJeu(pirate1 : Pirate, pirate2 : Pirate)  
    + distribuerCartesInitiales()  
    + appliquerEffetsCartes()  
    + defausserCartesPlateau()  
    + verifierFinPartie() : Boolean
    + determinerVainqueur() : Joueur
    + passerAuJoueurSuivant()  
    + setJoueurActif(index : Integer)  
    + getJoueurActif() : Integer
    + piocherCarte() : Carte
    + jouerCarte(carte : Carte) : Boolean
    + defausserCarte(indexCarte : Integer) : Boolean
    + getControlCartePlateau() : ControlCartePlateau
    + getControlPioche() : ControlPioche
    + getJoueur(index : Integer) : ControlJoueur
}

ControlJeu --> "1" Jeu : -jeu
ControlJeu --> "1" ControlPioche : -controlPioche
ControlJeu --> "1" ControlCartePlateau : -controlCartePlateau
ControlJeu --> "2" ControlJoueur : -controlJoueurs
ControlJeu --> "2" ControlZoneJoueur : -controlZoneJoueur1, -controlZoneJoueur2 

' Classe ControlJoueur
class ControlJoueur {
    
    --
    + ControlJoueur(joueur : Joueur, controlPioche : ControlPioche, controlZoneJoueur : ControlZoneJoueur)
    + initialiserMain()  
    + piocher() : Carte
    + jouerCarte(indexCarte : Integer) : Boolean
    + jouerCarte(carte : Carte) : Boolean
    + defausserCarte(indexCarte : Integer) : Boolean
    + perdrePointsDeVie(points : Integer)  
    + gagnerPointsDeVie(points : Integer)  
    + perdrePopularite(points : Integer)  
    + gagnerPopularite(points : Integer)  
    + perdreOr(montant : Integer) : Boolean
    + gagnerOr(montant : Integer)  
    + getMain() : List<Carte>
    + getJoueur() : Joueur
}
ControlJoueur --> "1" Joueur : -joueur
ControlJoueur --> "1" ControlPioche : -controlPioche
ControlJoueur --> "1" ControlZoneJoueur : -controlZoneJoueur

' Classe ControlCartePlateau
class ControlCartePlateau {
    
    --
    + ControlCartePlateau(controlJoueur1 : ControlJoueur, controlJoueur2 : ControlJoueur, zoneJoueur1 : ControlZoneJoueur, zoneJoueur2 : ControlZoneJoueur)
    + setJoueurs(controlJoueur1 : ControlJoueur, controlJoueur2 : ControlJoueur)  
    + appliquerEffetCarte()  
    + defausserCartesPlateau()  
}
ControlCartePlateau --> "2" ControlJoueur : -controlJoueur1, -controlJoueur2
ControlCartePlateau --> "2" ControlZoneJoueur : -zoneJoueur1, zoneJoueur2

' Classe ControlPioche
class ControlPioche {
    --
    + ControlPioche()
    + initialiserPioche()  
    + piocher() : Carte
    + estVide() : Boolean
    - chargerCartesDepuisRepertoire() : List<Carte>
}
ControlPioche --> "1" Pioche : -pioche

' Classe ControlZoneJoueur
class ControlZoneJoueur {

    --
    + ControlZoneJoueur(zoneOffensive : ZoneOffensive, zoneStrategique : ZoneStrategique)
    + ajouterCarteOffensive(carte : CarteOffensive)  
    + ajouterCarteStrategique(carte : CarteStrategique)  
    + viderZone()  
    + getZoneOffensive() : ZoneOffensive
    + getZoneStrategique() : ZoneStrategique
}
ControlZoneJoueur --> "1" ZoneOffensive : -zoneOffensive
ControlZoneJoueur --> "1" ZoneStrategique : -zoneStrategique

class BoundaryJeu {
    - scan : Scanner
    --
    + BoundaryJeu(controlJeu : ControlJeu)
    + afficherMessage()  
    + lancerJeu()  
    + afficherRegles()  
    + demarrerJeu()  
    + jouerPartie()  
    + fermer()  
    --
    # demanderPirate(numeroJoueur : Integer) : Pirate
    + static getPiratesDisponibles() : List<Pirate>
    --
    - demanderContinuerIteration() : Boolean
    - jouerCarte(carte : Carte)  
    - afficherResultatFinal()  
}
BoundaryJeu --> "1" ControlJeu : -controlJeu
@enduml