/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ihm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.RenderingHints;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import joueur.Joueur;

/**
 *
 * @author Fonteyne
 */
public class PanelInformations extends javax.swing.JPanel {
    private static Image imageVie;
    private static Image imagePopularite;
    private static Image imageOr;
    private final Joueur joueur;
    private static final int TAILLE_ICONE = 30;
    private static final int ESPACE_HORIZONTAL = 5;
    private static final int ESPACE_VERTICAL = 30;
    
    
    public PanelInformations(Joueur joueur) {
        this.joueur = joueur;
        setBackground(Color.red);
        setOpaque(false);
        setVisible(true);
        
        try {
            imageVie = ImageIO.read(new File("src/ressources/icones/heart_red/heart_red_base.png"));
            imagePopularite = ImageIO.read(new File("src/ressources/icones/star/star_base.png"));
            imageOr = ImageIO.read(new File("src/ressources/icones/or/or.png"));
        } catch (IOException e) {
            System.err.println("Erreur de chargement des images: " + e.getMessage());
            // Gestion d'erreur plus robuste
            JOptionPane.showMessageDialog(null, 
                "Impossible de charger les ressources graphiques", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (imageVie == null || imagePopularite == null || imageOr == null) {
            g.setColor(Color.RED);
            g.drawString("Ressources manquantes !", 10, 10);
            return;
        }

        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        
        try{
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, new File("src/ressources/fonts/Pieces_of_Eight.ttf")).deriveFont(25f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(customFont);
            
            g2.setFont(customFont.deriveFont(25f));
        }catch (FontFormatException | IOException e) {
            e.printStackTrace(); 
        }
        

        //Points de vie
        dessinerStat(g2, joueur.getPointsDeVie(), imageVie, 0);

        //Popularité 
        dessinerStat(g2, joueur.getPopularite(), imagePopularite, ESPACE_VERTICAL);

        //Or 
        dessinerStat(g2, joueur.getOr(), imageOr, ESPACE_VERTICAL * 2);

        g2.dispose();
    }

    private void dessinerStat(Graphics2D g2, int valeur, Image icone, int y) {
        if (valeur <= 5) {
            for (int i = 0; i < valeur; i++) {
                g2.drawImage(icone, i * (TAILLE_ICONE + ESPACE_HORIZONTAL), y, TAILLE_ICONE, TAILLE_ICONE, null);
            }
        } else {
            //Affichage condensé (une icône + nombre)
            g2.drawImage(icone, 0, y, TAILLE_ICONE, TAILLE_ICONE, null);
            g2.setColor(Color.BLACK);
            g2.drawString(String.valueOf(valeur), TAILLE_ICONE + 5, y + TAILLE_ICONE - 5);
            
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
